version = 1

test_patterns = ["**/*.sh"]

[[analyzers]]
enabled = true
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["hermes/Dockerfile"]

[[analyzers]]
enabled = true
name = "shell"

  [analyzers.meta]
  dialect = "bash"

[[transformers]]
enabled = true
name = "prettier"
