= Features
:toc:
:toclevels: 2
:showtitle:
:homepage: https://github.com/Andevour/i3buntu
:version: 0.1.0

== Overview

This file exists to give you a comprehensive overview over all features i3buntu either provides you with or improves upon. There are dozens of smaller improvements, which are going to be listed here as well. Make sure your read this page to know what you will get when using i3buntu.

== Core features

=== Design

==== Window Manager

The most obvious change, as it affects the design of your system, is the choice of i3. For itself, i3 is very ugly - but to be fair, this is where i3buntu comes into play. The configuration has been done meticulously.

// [[i3]]
// image::https://upload.wikimedia.org/wikipedia/commons/2/27/I3_window_manager_logo.svg[i3,500]

==== Color scheme

The color scheme has been carefully chosen to implement into the system seamlessly. Every program, from the shell to your browser have adapted these changes. They are reflected in the choice of icons, backgrounds and windows. The _Adapta GTK_ color theme enhances this experience. If you are curious about the used color and their values, look no further than `resources/design`. If you would like to make your own version, consult these link:https://digitalsynopsis.com/design/minimal-web-color-palettes-combination-hex-code/[premade colors] or this link:https://coolors.co/[color generator]. The link:../design/color_palette.pdf[`color_palette.pdf`] gives insight about the RGB, YMCK, HEX and HSV values. If you just want to stare at them, here they are

[[color_scheme]]
image::../design/color_palette.svg[color scheme]

=== Performance

==== No desktop environment

While GNOME and KDE can be beautiful as well, they are nonetheless heavier on resources. Today, this may not seem like much of a problem, and indeed, it isn't, but for some, getting the best performance out of their system matters. 

==== Low memory consumption

When under idle, the system uses about 310+ MiB of RAM. That is roughly one tenth of what Windows 10 uses, and less than a third of GNOME. 

== Developer features

==== Visual Studio Code

During the packaging stage, the user is offered a wide variety of choices, what to install and what not to install. From these many choices, Visual Studio Code is one of them. One of the most popular and lightweight IDEs, VS Code provides customizability and ease of use.

Moreover, if you chose to install VS Code, you will have the opportunity to pick up hand-selected extensions afterwards. The selection of these extensions can be found in this link:../sys/vscode/README.adoc[README] file.

==== JetBrains' IDEs

IntelliJ, PyCharm and CLion can be installed, next to Kotlin. These IDEs are the go-to option for workloads and large projects in Java, Python, C, C++, RUST. If you are interested in other languages, there sure is a specialized version in link:https://www.jetbrains.com/[JetBrains] homepage. With the link:https://education.github.com/[GitHub Students Developer Pack], these professional solutions are free of charge while you are studying.

==== Docker, RUST & NeoVIM

Since _v0.9.2-beta1_, Docker and NeoVIM can be chosen as an installation candidate. The installation of RUST is analogous to all the other installations mentioned.

== Extension features

=== Proper BASH setup & aliases

_BASH_, or _Bourne-Again Shell_, is the default shell under _Ubuntu_. It alone is extremely powerful - as a shell should be, obviously...

With the `.bashrc` and `.bash_aliases`, _BASH_ is being extend through rich functionality. The rc-file sets up parameters, like the PS1/prompt design `[user@host] : [ directory ] $`, auto-cd via `shopt -s autocd` or more friendly `less`.

[[BASH]]
image::https://upload.wikimedia.org/wikipedia/commons/8/82/Gnu-bash-logo.svg[BASH, 500]

The aliases file brings *a few* handy aliases and functions. The aliases list is rather long - you should see it yourself, but noteworthy would be `lsa` to list everything like `ls -lhs`, `...` to go two directories back or `sd` as in show disks (`blkid -o list`).

Exported functions include `a` for `sudo apt-get $1 ...`, `sf` as in search file for  `ls -lha | grep $1`, `open`, to open the pdf viewer evince from the command line. Most notably is the `update` function, which updated all components of your system, whether it be via APT, snap or rustup.
