version: '3.8'

services:

  forward:
    image: andevour/hermes:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        # ? Router
        - traefik.http.routers.hermes.rule=Host(`apollo.itbsd.com`)
        - traefik.http.routers.hermes.entrypoints=https
        # ? Middleware
        - traefik.http.routers.hermes.middlewares=secureHeaders@file
        # ? Service
        - traefik.http.services.hermes.loadbalancer.server.port=8080
        - traefik.http.services.hermes.loadbalancer.server.scheme=http

networks:
  traefik:
    external: true
